### ISSUE TITLE
Code Smells

### ISSUE THREAD

**Issue by danielmolinas** [eogle1/CS361-Repository#1]
Long main function. It should be split into smaller functions.

main function has multiple jobs. main function processes input, makes network requests, parses responses, and handles program termination, the function should be split into smaller functions.

**Comment by eogle1** [comment]
There are a few places where I couldn't quite get the functions under 10 lines, but they're all pretty close now.

**Comment by eogle1** [comment]
A few functions are a little longer than 10 lines, but they're pretty close, so I think this ought to work?
